// Generated package metadata: the loader must describe the binaries selected
// by staging, not guess their signature status from the npm version.
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

export async function writeChannel(channel) {
  if (channel !== "signed" && channel !== "dev") throw new Error(`Unknown channel: ${channel}`);
  const manifest = JSON.parse(await readFile(path.join(packageRoot,
    channel === "dev" ? "artifacts-dev.json" : "artifacts.json"), "utf8"));
  // The blob handler enters signed community builds with DuckHTS 1.5.3.
  const [major, minor, patch] = manifest.duckhts.split(".").map(Number);
  const blobCapable = channel === "dev" || major > 1 || (major === 1 &&
    (minor > 5 || (minor === 5 && patch >= 3)));
  await writeFile(path.join(packageRoot, "src/channel.js"),
    `// Generated by scripts/channel.mjs for the ${channel} channel.\n` +
    `export const SIGNED = ${channel === "signed"};\n` +
    `export const BLOB_CAPABLE = ${blobCapable};\n`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await writeChannel(process.env.DUCKHTS_NPM_CHANNEL ?? "signed");
}
