#!/usr/bin/env Rscript
args <- commandArgs(trailingOnly = TRUE)
root <- normalizePath(Sys.getenv("DUCKHTS_ROOT", unset = "."), mustWork = TRUE)
package_root <- file.path(root, "r", "duckhtsbench")
if (!nzchar(Sys.getenv("DUCKHTSBENCH_REGISTRY", unset = ""))) Sys.setenv(DUCKHTSBENCH_REGISTRY = file.path(package_root, "inst", "benchmark_registry.tsv"))
for (file in c("registry.R", "stage.R", "liftover.R")) source(file.path(package_root, "R", file))
base_dir <- if (length(args)) args[[1L]] else duckhts_bench_cache_path("references/liftover/grch37-to-grch38")
paths <- duckhts_bench_stage_liftover(base_dir, Sys.getenv("SAMTOOLS_BIN", unset = Sys.which("samtools")), Sys.getenv("GZIP_BIN", unset = Sys.which("gzip")))
cat(sprintf("Liftover references staged under: %s\nProvenance: %s\n", base_dir, file.path(base_dir, "provenance.tsv")))
cat(sprintf("LIFTOVER_CHAIN_PATH=%s\nLIFTOVER_SRC_FASTA=%s\nLIFTOVER_DST_FASTA=%s\n", paths[["chain"]], paths[["source_fasta"]], paths[["destination_fasta"]]))
