#!/usr/bin/env perl
# Generate SO term metadata from VEP's extracted %OVERLAP_CONSEQUENCES table and
# duckvep's explicit stable bit-binding ledger.
use strict;
use warnings;

my $check = 0;
my $target;
for my $arg (@ARGV) {
    if ($arg eq '--check') { $check = 1; }
    elsif (!defined $target) { $target = $arg; }
    else { die "usage: $0 [--check] [target]\n"; }
}

my $spec_path = 'test/duckvep/conformance/data/so_consequences.tsv';
my $bindings_path = 'test/duckvep/conformance/data/so_bit_bindings.tsv';
my %impact_c = (
    HIGH => 'DUCKVEP_IMPACT_HIGH',
    MODERATE => 'DUCKVEP_IMPACT_MODERATE',
    LOW => 'DUCKVEP_IMPACT_LOW',
    MODIFIER => 'DUCKVEP_IMPACT_MODIFIER',
);

sub read_tsv {
    my ($path) = @_;
    open my $fh, '<', $path or die "cannot open $path: $!";
    my $header = <$fh>;
    defined $header or die "$path is empty\n";
    chomp $header;
    my @cols = split /\t/, $header, -1;
    my @rows;
    while (my $line = <$fh>) {
        chomp $line;
        next if $line eq '';
        my @v = split /\t/, $line, -1;
        die "$path: wrong field count\n" if @v != @cols;
        my %r;
        @r{@cols} = @v;
        push @rows, \%r;
    }
    return \@rows;
}

my $spec = read_tsv($spec_path);
my $bindings = read_tsv($bindings_path);
my %spec_by_term;
for my $r (@$spec) {
    die "duplicate SO term in $spec_path: $r->{SO_term}\n"
        if exists $spec_by_term{$r->{SO_term}};
    $spec_by_term{$r->{SO_term}} = $r;
}

my @rows;
my (%seen_term, %seen_enum);
for my $b (@$bindings) {
    my $term = $b->{SO_term};
    my $enum = $b->{so_enum};
    die "duplicate SO binding term: $term\n" if $seen_term{$term}++;
    die "duplicate SO binding enum: $enum\n" if $seen_enum{$enum}++;
    die "invalid SO enum for $term\n" unless $enum =~ /^DUCKVEP_SO_[A-Z0-9_]+$/;
    my $s = $spec_by_term{$term} or die "SO binding absent from VEP spec: $term\n";
    die "invalid tier for $term\n" unless $s->{tier} =~ /^[1-4]$/;
    die "invalid rank for $term\n" unless $s->{rank} =~ /^\d+$/ && $s->{rank} <= 255;
    die "invalid impact for $term: $s->{impact}\n" unless exists $impact_c{$s->{impact}};
    push @rows, { %$b, %$s };
}

my $text = "/* GENERATED by test/duckvep/conformance/generate_so_metadata.pl from\n" .
           " * test/duckvep/conformance/data/so_consequences.tsv (VEP metadata) and\n" .
           " * test/duckvep/conformance/data/so_bit_bindings.tsv (stable public bit bindings).\n" .
           " * Do not hand-edit. */\n";
$text .= sprintf("enum { DUCKVEP_GENERATED_SO_BINDING_COUNT = %du };\n", scalar @rows);
$text .= "static const struct duckvep_so_metadata k_so[DUCKVEP_SO_BIT_COUNT] = {\n";
for my $r (@rows) {
    $text .= sprintf(
        "    [%s] = { \"%s\", %s, %su, %su },\n",
        $r->{so_enum}, $r->{SO_term}, $impact_c{$r->{impact}}, $r->{rank}, $r->{tier});
}
$text .= "};\n\n";
$text .= "static const duckvep_so_bit_t k_so_render_order[DUCKVEP_SO_BIT_COUNT] = {\n";
for my $r (sort { $a->{rank} <=> $b->{rank} } @rows) {
    $text .= "    $r->{so_enum},\n";
}
$text .= "};\n";

if ($check) {
    die "--check requires target path\n" unless defined $target;
    open my $fh, '<', $target or die "cannot open generated target $target: $!";
    local $/;
    my $actual = <$fh>;
    die "$target is stale; regenerate with: perl $0 > $target\n" if $actual ne $text;
    exit 0;
}

if (defined $target) {
    open my $fh, '>', $target or die "cannot write $target: $!";
    print {$fh} $text;
    close $fh or die "cannot close $target: $!";
} else {
    print $text;
}
