#!/usr/bin/env perl
# Generate the compiled consequence rule program from VEP class-model metadata plus
# an explicit duckvep predicate-fact binding ledger. No Perl module loading: the
# VEP-derived data has already been extracted under test/duckvep/conformance/data.
use strict;
use warnings;

my $check = 0;
my $target;
for my $arg (@ARGV) {
    if ($arg eq '--check') { $check = 1; }
    elsif (!defined $target) { $target = $arg; }
    else { die "usage: $0 [--check] [target]\n"; }
}

my $spec_path = 'test/duckvep/conformance/data/so_consequences.tsv';
my $bindings_path = 'test/duckvep/conformance/data/effect_rule_bindings.tsv';
my %impact_c = (
    HIGH => 'DUCKVEP_IMPACT_HIGH',
    MODERATE => 'DUCKVEP_IMPACT_MODERATE',
    LOW => 'DUCKVEP_IMPACT_LOW',
    MODIFIER => 'DUCKVEP_IMPACT_MODIFIER',
);

sub read_tsv {
    my ($path) = @_;
    open my $fh, '<', $path or die "cannot open $path: $!";
    my $header = <$fh>;
    defined $header or die "$path is empty\n";
    chomp $header;
    my @cols = split /\t/, $header, -1;
    my @rows;
    while (my $line = <$fh>) {
        chomp $line;
        next if $line eq '';
        my @v = split /\t/, $line, -1;
        die "$path: wrong field count\n" if @v != @cols;
        my %r;
        @r{@cols} = @v;
        push @rows, \%r;
    }
    return \@rows;
}

my $spec = read_tsv($spec_path);
my $bindings = read_tsv($bindings_path);
my %spec_by_term;
for my $r (@$spec) {
    die "duplicate SO term in $spec_path: $r->{SO_term}\n"
        if exists $spec_by_term{$r->{SO_term}};
    $spec_by_term{$r->{SO_term}} = $r;
}

my @rules;
my %seen;
my %fast_by_pre;
for my $b (@$bindings) {
    my $term = $b->{SO_term};
    die "duplicate binding: $term\n" if $seen{$term}++;
    my $s = $spec_by_term{$term} or die "binding absent from VEP spec: $term\n";
    die "invalid SO enum for $term\n" unless $b->{so_enum} =~ /^DUCKVEP_SO_[A-Z0-9_]+$/;
    die "invalid tier for $term\n" unless $s->{tier} =~ /^[1-4]$/;
    die "invalid rank for $term\n" unless $s->{rank} =~ /^\d+$/ && $s->{rank} <= 255;
    die "invalid impact for $term: $s->{impact}\n" unless exists $impact_c{$s->{impact}};
    die "empty C binding for $term\n" unless $b->{required} ne '' && $b->{forbidden} ne '';
    my %rule = (%$b, %$s);
    die "optimized rule requires one PRE bit for $term: $b->{required}\n"
        unless $b->{required} =~ /^DUCKVEP_PRE\((DUCKVEP_PRE_[A-Z0-9_]+)\)$/;
    $rule{pre_enum} = $1;
    die "optimized rule requires an empty forbidden mask for $term\n"
        unless $b->{forbidden} eq '0u';
    die "multiple consequences bound to $rule{pre_enum}\n"
        if exists $fast_by_pre{$rule{pre_enum}};
    $fast_by_pre{$rule{pre_enum}} = \%rule;
    push @rules, \%rule;
}
@rules = sort { $a->{tier} <=> $b->{tier} || $a->{rank} <=> $b->{rank} } @rules;

my $text = "/* GENERATED by test/duckvep/conformance/generate_effect_rules.pl from\n" .
           " * test/duckvep/conformance/data/so_consequences.tsv (VEP metadata) and\n" .
           " * test/duckvep/conformance/data/effect_rule_bindings.tsv (ported predicate facts).\n" .
           " * Do not hand-edit. */\n";
$text .= "static const duckvep_consequence_rule_t k_rules[] = {\n";
for my $r (@rules) {
    $text .= sprintf(
        "    { %s, %s, DUCKVEP_SO(%s), %su, %su, %s }, /* %s / %s */\n",
        $r->{required}, $r->{forbidden}, $r->{so_enum}, $r->{tier}, $r->{rank},
        $impact_c{$r->{impact}}, $r->{SO_term}, $r->{predicate});
}
$text .= "};\n";

# The production evaluator iterates only facts that can emit a consequence.
# Keep the general rule interpreter as the test oracle; generation fails if a
# future rule needs compound required/forbidden predicates, so the optimized
# representation can never silently change the VEP tier machine.
$text .= "static const uint64_t k_rule_so_by_pre_bit[DUCKVEP_PRE_BIT_COUNT] = {\n";
for my $r (@rules) {
    $text .= sprintf(
        "    [%s] = DUCKVEP_SO(%s),\n",
        $r->{pre_enum}, $r->{so_enum});
}
$text .= "};\n";

for my $group (1, 2, 3) {
    my @members = grep {
        $group == 3 ? $_->{tier} >= 3 : $_->{tier} == $group
    } @rules;
    my $name = $group == 3 ? 'fallback' : "tier$group";
    my $expr = @members
        ? join(" |\n        ", map { $_->{required} } @members)
        : 'UINT64_C(0)';
    $text .= "static const uint64_t k_rule_${name}_pre_mask =\n        $expr;\n";
}

# OverlapConsequence metadata restricts several transcript predicates to an
# ordinary VariationFeature. StructuralVariationFeature inherits only the rules
# declared for BaseVariationFeature. Generate that distinction from the pinned
# VEP table so the C evaluator cannot drift into a hand-maintained term list.
my @structural = grep {
    $_->{variant_feature_class} eq
        'Bio::EnsEMBL::Variation::BaseVariationFeature'
} @rules;
my $structural_expr = @structural
    ? join(" |\n        ", map { $_->{required} } @structural)
    : 'UINT64_C(0)';
$text .= "static const uint64_t k_rule_structural_pre_mask =\n" .
         "        $structural_expr;\n";

if ($check) {
    die "--check requires target path\n" unless defined $target;
    open my $fh, '<', $target or die "cannot open generated target $target: $!";
    local $/;
    my $actual = <$fh>;
    die "$target is stale; regenerate with: perl $0 > $target\n" if $actual ne $text;
    exit 0;
}

if (defined $target) {
    open my $fh, '>', $target or die "cannot write $target: $!";
    print {$fh} $text;
    close $fh or die "cannot close $target: $!";
} else {
    print $text;
}
