#!/usr/bin/env perl
# Generate the compiled consequence rule program from VEP class-model metadata plus
# an explicit duckvep predicate-fact binding ledger. No Perl module loading: the
# VEP-derived data has already been extracted under test/duckvep/conformance/data.
use strict;
use warnings;

my $check = 0;
my $target;
for my $arg (@ARGV) {
    if ($arg eq '--check') { $check = 1; }
    elsif (!defined $target) { $target = $arg; }
    else { die "usage: $0 [--check] [target]\n"; }
}

my $spec_path = 'test/duckvep/conformance/data/so_consequences.tsv';
my $bindings_path = 'test/duckvep/conformance/data/effect_rule_bindings.tsv';
my %impact_c = (
    HIGH => 'DUCKVEP_IMPACT_HIGH',
    MODERATE => 'DUCKVEP_IMPACT_MODERATE',
    LOW => 'DUCKVEP_IMPACT_LOW',
    MODIFIER => 'DUCKVEP_IMPACT_MODIFIER',
);

sub read_tsv {
    my ($path) = @_;
    open my $fh, '<', $path or die "cannot open $path: $!";
    my $header = <$fh>;
    defined $header or die "$path is empty\n";
    chomp $header;
    my @cols = split /\t/, $header, -1;
    my @rows;
    while (my $line = <$fh>) {
        chomp $line;
        next if $line eq '';
        my @v = split /\t/, $line, -1;
        die "$path: wrong field count\n" if @v != @cols;
        my %r;
        @r{@cols} = @v;
        push @rows, \%r;
    }
    return \@rows;
}

my $spec = read_tsv($spec_path);
my $bindings = read_tsv($bindings_path);
my %spec_by_term;
for my $r (@$spec) {
    die "duplicate SO term in $spec_path: $r->{SO_term}\n"
        if exists $spec_by_term{$r->{SO_term}};
    $spec_by_term{$r->{SO_term}} = $r;
}

my @rules;
my %seen;
for my $b (@$bindings) {
    my $term = $b->{SO_term};
    die "duplicate binding: $term\n" if $seen{$term}++;
    my $s = $spec_by_term{$term} or die "binding absent from VEP spec: $term\n";
    die "invalid SO enum for $term\n" unless $b->{so_enum} =~ /^DUCKVEP_SO_[A-Z0-9_]+$/;
    die "invalid tier for $term\n" unless $s->{tier} =~ /^[1-4]$/;
    die "invalid rank for $term\n" unless $s->{rank} =~ /^\d+$/ && $s->{rank} <= 255;
    die "invalid impact for $term: $s->{impact}\n" unless exists $impact_c{$s->{impact}};
    die "empty C binding for $term\n" unless $b->{required} ne '' && $b->{forbidden} ne '';
    push @rules, { %$b, %$s };
}
@rules = sort { $a->{tier} <=> $b->{tier} || $a->{rank} <=> $b->{rank} } @rules;

my $text = "/* GENERATED by test/duckvep/conformance/generate_effect_rules.pl from\n" .
           " * test/duckvep/conformance/data/so_consequences.tsv (VEP metadata) and\n" .
           " * test/duckvep/conformance/data/effect_rule_bindings.tsv (ported predicate facts).\n" .
           " * Do not hand-edit. */\n";
$text .= "static const duckvep_consequence_rule_t k_rules[] = {\n";
for my $r (@rules) {
    $text .= sprintf(
        "    { %s, %s, DUCKVEP_SO(%s), %su, %su, %s }, /* %s / %s */\n",
        $r->{required}, $r->{forbidden}, $r->{so_enum}, $r->{tier}, $r->{rank},
        $impact_c{$r->{impact}}, $r->{SO_term}, $r->{predicate});
}
$text .= "};\n";

if ($check) {
    die "--check requires target path\n" unless defined $target;
    open my $fh, '<', $target or die "cannot open generated target $target: $!";
    local $/;
    my $actual = <$fh>;
    die "$target is stale; regenerate with: perl $0 > $target\n" if $actual ne $text;
    exit 0;
}

if (defined $target) {
    open my $fh, '>', $target or die "cannot write $target: $!";
    print {$fh} $text;
    close $fh or die "cannot close $target: $!";
} else {
    print $text;
}
