#include "duckhts_somalier.h"
#include "duckhts_registration.h"

/* Per-sample panel coverage is checked with the row count plus the sum and XOR of
   a 64-bit hash of site_index against the panel's: a per-sample DISTINCT set
   would hold samples x sites entries. Missing or repeated ordinals therefore
   pass only by an accidental collision of both hashes.

   Genetic-sex evidence from X/Y dosage, following Somalier v0.3.4
   (ff58fdade8f4f8293d904f10e0a4a13f1fac808d) relate.nim: fill_sample_info
   for the X/Y depth and genotype statistics, and the sex and Y-signal
   checks in the pedigree pass. Depth is normalised by the mean A+B depth of
   the autosomal sites that pass the relatedness allele-balance gate. */
bool register_duckhts_somalier_sex_sql(duckhts_registration_t *registration) {
    static const char *const sex_sql[] = {
        "CREATE OR REPLACE MACRO duckhts_somalier_sex("
        "counts_table, panel_table, min_depth := 7, min_sex_site_depth := 7, "
        "min_het_balance := 0.3, hom_balance_cutoff := 0.01, "
        "min_usable_x_sites := 11, xy_max_het_ratio := 0.05, "
        "xx_min_het_ratio := 0.4, y_signal_min := 0.4, y_gate := 'sample') AS TABLE "
        "WITH __dht_settings AS MATERIALIZED (SELECT CASE "
        "WHEN min_depth IS NULL OR min_sex_site_depth IS NULL "
        "OR TRY_CAST(min_depth AS HUGEINT) IS NULL "
        "OR TRY_CAST(min_sex_site_depth AS HUGEINT) IS NULL "
        "OR TRY_CAST(min_depth AS HUGEINT) NOT BETWEEN 1 AND 4294967295 "
        "OR TRY_CAST(min_sex_site_depth AS HUGEINT) NOT BETWEEN 1 AND 4294967295 "
        "OR TRY_CAST(min_depth AS DOUBLE) != TRY_CAST(min_depth AS HUGEINT) "
        "OR TRY_CAST(min_sex_site_depth AS DOUBLE) != TRY_CAST(min_sex_site_depth AS HUGEINT) THEN "
        "error('duckhts_somalier_sex: min_depth and min_sex_site_depth must be integers in "
        "[1, 4294967295]') "
        "WHEN min_het_balance IS NULL OR hom_balance_cutoff IS NULL "
        "OR NOT isfinite(CAST(min_het_balance AS DOUBLE)) "
        "OR NOT isfinite(CAST(hom_balance_cutoff AS DOUBLE)) "
        "OR CAST(min_het_balance AS DOUBLE) <= 0 OR CAST(min_het_balance AS DOUBLE) > 0.5 "
        "OR CAST(hom_balance_cutoff AS DOUBLE) < 0 "
        "OR CAST(hom_balance_cutoff AS DOUBLE) > CAST(min_het_balance AS DOUBLE) THEN "
        "error('duckhts_somalier_sex: allele-balance limits must satisfy "
        "0 <= hom_balance_cutoff <= min_het_balance <= 0.5') "
        "WHEN min_usable_x_sites IS NULL OR TRY_CAST(min_usable_x_sites AS HUGEINT) IS NULL "
        "OR TRY_CAST(min_usable_x_sites AS HUGEINT) NOT BETWEEN 1 AND 100000000 THEN "
        "error('duckhts_somalier_sex: min_usable_x_sites must be an integer in "
        "[1, 100000000]') "
        "WHEN xy_max_het_ratio IS NULL OR xx_min_het_ratio IS NULL OR y_signal_min IS NULL "
        "OR NOT isfinite(CAST(xy_max_het_ratio AS DOUBLE)) "
        "OR NOT isfinite(CAST(xx_min_het_ratio AS DOUBLE)) "
        "OR NOT isfinite(CAST(y_signal_min AS DOUBLE)) "
        "OR CAST(xy_max_het_ratio AS DOUBLE) < 0 "
        "OR CAST(xy_max_het_ratio AS DOUBLE) > CAST(xx_min_het_ratio AS DOUBLE) "
        "OR CAST(y_signal_min AS DOUBLE) < 0 THEN "
        "error('duckhts_somalier_sex: thresholds must be finite with "
        "0 <= xy_max_het_ratio <= xx_min_het_ratio and y_signal_min >= 0') "
        "WHEN y_gate IS NULL OR CAST(y_gate AS VARCHAR) NOT IN ('sample', 'cohort') THEN "
        "error('duckhts_somalier_sex: y_gate must be sample or cohort') "
        "ELSE true END AS valid"
        "), __dht_panel AS MATERIALIZED ("
        "SELECT CAST(assembly AS VARCHAR) AS assembly, "
        "CAST(site_index AS UBIGINT) AS site_index, CAST(region AS VARCHAR) AS region, "
        "CAST(position AS UBIGINT) AS position, CAST(allele_a AS VARCHAR) AS allele_a, "
        "CAST(allele_b AS VARCHAR) AS allele_b FROM query_table(panel_table)"
        "), __dht_identity AS MATERIALIZED (SELECT "
        "duckhts_somalier_panel_sha256(panel_table) AS panel_sha256, "
        "count(*)::UBIGINT AS site_count, "
        "sum(CAST(hash(site_index) AS HUGEINT)) AS ordinal_hash_sum, "
        "bit_xor(hash(site_index)) AS ordinal_hash_xor, "
        "count(*) FILTER (WHERE region NOT IN " DUCKHTS_SOMALIER_SEX_REGIONS_SQL ")::UBIGINT "
        "AS autosomal_sites, "
        "count(*) FILTER (WHERE region IN " DUCKHTS_SOMALIER_X_REGIONS_SQL ")::UBIGINT "
        "AS x_sites FROM __dht_panel",
        "), __dht_counts AS NOT MATERIALIZED ("
        "SELECT CAST(sample_id AS VARCHAR) AS sample_id, "
        "CAST(assembly AS VARCHAR) AS assembly, CAST(site_index AS UBIGINT) AS site_index, "
        "CAST(region AS VARCHAR) AS region, CAST(position AS UBIGINT) AS position, "
        "CAST(allele_a AS VARCHAR) AS allele_a, CAST(allele_b AS VARCHAR) AS allele_b, "
        "CAST(a AS UBIGINT) AS a, CAST(b AS UBIGINT) AS b, CAST(other AS UBIGINT) AS other "
        "FROM query_table(counts_table)"
        "), __dht_checked AS NOT MATERIALIZED (SELECT c.*, p.assembly AS panel_assembly, "
        "p.region AS panel_region, p.position AS panel_position, "
        "p.allele_a AS panel_allele_a, p.allele_b AS panel_allele_b "
        "FROM __dht_counts c LEFT JOIN __dht_panel p USING (site_index)",
        "), __dht_validation AS MATERIALIZED (SELECT CASE "
        "WHEN count(*) = 0 THEN error('duckhts_somalier_sex: counts are empty') "
        "WHEN count(*) FILTER (WHERE sample_id IS NULL OR sample_id = '' "
        "OR assembly IS NULL OR site_index IS NULL OR region IS NULL OR position IS NULL "
        "OR allele_a IS NULL OR allele_b IS NULL) != 0 THEN "
        "error('duckhts_somalier_sex: count identity fields cannot be NULL') "
        "WHEN count(*) FILTER (WHERE panel_assembly IS NULL OR assembly != panel_assembly "
        "OR region != panel_region OR position != panel_position "
        "OR allele_a != panel_allele_a OR allele_b != panel_allele_b) != 0 THEN "
        "error('duckhts_somalier_sex: count site geometry or A/B orientation does not "
        "match the ordered panel') "
        "WHEN count(*) FILTER (WHERE (a IS NULL) != (b IS NULL) "
        "OR (a IS NULL) != (other IS NULL)) != 0 THEN "
        "error('duckhts_somalier_sex: counts must be all measured or all unavailable') "
        "WHEN count(*) FILTER (WHERE a > 4294967295 OR b > 4294967295 "
        "OR other > 4294967295) != 0 THEN "
        "error('duckhts_somalier_sex: measured counts must fit UINTEGER') "
        "WHEN (SELECT count(*) FROM (SELECT sample_id FROM __dht_checked GROUP BY sample_id "
        "HAVING count(*) != (SELECT site_count FROM __dht_identity) "
        "OR sum(CAST(hash(site_index) AS HUGEINT)) != "
        "(SELECT ordinal_hash_sum FROM __dht_identity) "
        "OR bit_xor(hash(site_index)) != (SELECT ordinal_hash_xor FROM __dht_identity))) "
        "!= 0 THEN "
        "error('duckhts_somalier_sex: every sample requires one count row for every "
        "panel site') ELSE true END AS valid FROM __dht_checked"
        "), __dht_sites AS NOT MATERIALIZED (SELECT c.sample_id, c.assembly, "
        "CASE WHEN c.region IN " DUCKHTS_SOMALIER_X_REGIONS_SQL " THEN 'X' "
        "WHEN c.region IN " DUCKHTS_SOMALIER_SEX_REGIONS_SQL " THEN 'Y' "
        "ELSE 'A' END AS kind, c.a, c.b, c.other, c.a + c.b AS depth, "
        "CASE WHEN c.a + c.b + c.other = 0 THEN 0.0 "
        "ELSE CAST(c.other AS DOUBLE) / CAST(c.a + c.b + c.other AS DOUBLE) END AS other_fraction, "
        "CASE WHEN c.a IS NULL OR c.a + c.b = 0 THEN NULL "
        "ELSE CAST(c.b AS DOUBLE) / CAST(c.a + c.b AS DOUBLE) END AS balance "
        "FROM __dht_checked c CROSS JOIN __dht_validation v WHERE v.valid",
        "), __dht_calls AS NOT MATERIALIZED (SELECT s.*, "
        "CASE WHEN kind = 'A' THEN NULL WHEN a IS NULL OR other_fraction > 0.04 "
        "OR depth < CAST(min_sex_site_depth AS UBIGINT) THEN -1 "
        "WHEN a = 0 THEN 2 WHEN b = 0 THEN 0 "
        "WHEN balance < CAST(hom_balance_cutoff AS DOUBLE) THEN 0 "
        "WHEN balance > 1 - CAST(hom_balance_cutoff AS DOUBLE) THEN 2 "
        "WHEN balance >= CAST(min_het_balance AS DOUBLE) "
        "AND balance <= 1 - CAST(min_het_balance AS DOUBLE) THEN 1 "
        "ELSE -1 END AS alt_count, "
        "kind = 'A' AND a IS NOT NULL AND other_fraction <= 0.1 "
        "AND depth >= CAST(min_depth AS UBIGINT) AS genotyped "
        "FROM __dht_sites s"
        "), __dht_samples AS MATERIALIZED (SELECT sample_id, min(assembly) AS assembly, "
        "count(*) FILTER (WHERE genotyped) AS autosomal_genotyped_sites, "
        "avg(CAST(depth AS DOUBLE)) FILTER (WHERE genotyped) AS autosomal_depth_mean, "
        "count(*) FILTER (WHERE kind = 'X' AND alt_count >= 0) AS x_usable_sites, "
        "count(*) FILTER (WHERE kind = 'X' AND alt_count = 0) AS x_hom_ref, "
        "count(*) FILTER (WHERE kind = 'X' AND alt_count = 1) AS x_het, "
        "count(*) FILTER (WHERE kind = 'X' AND alt_count = 2) AS x_hom_alt, "
        "avg(CAST(depth AS DOUBLE)) FILTER (WHERE kind = 'X' AND alt_count >= 0) AS x_depth_mean, "
        "count(*) FILTER (WHERE kind = 'Y') AS y_sites, "
        "count(*) FILTER (WHERE kind = 'Y' AND alt_count >= 0) AS y_usable_sites, "
        "avg(CAST(depth AS DOUBLE)) FILTER (WHERE kind = 'Y' AND alt_count >= 0) AS y_depth_mean "
        "FROM __dht_calls GROUP BY sample_id",
        "), __dht_ratios AS NOT MATERIALIZED (SELECT s.*, "
        "CASE WHEN autosomal_genotyped_sites = 0 OR x_usable_sites = 0 THEN NULL "
        "ELSE 2 * x_depth_mean / autosomal_depth_mean END AS x_depth_ratio, "
        "CASE WHEN autosomal_genotyped_sites = 0 OR y_usable_sites = 0 THEN NULL "
        "ELSE 2 * y_depth_mean / autosomal_depth_mean END AS y_depth_ratio, "
        "CASE WHEN x_usable_sites = 0 THEN NULL WHEN x_hom_alt = 0 THEN "
        "CASE WHEN x_het = 0 THEN NULL ELSE CAST('Infinity' AS DOUBLE) END "
        "ELSE CAST(x_het AS DOUBLE) / CAST(x_hom_alt AS DOUBLE) END AS x_het_hom_alt_ratio "
        "FROM __dht_samples s"
        "), __dht_cohort AS MATERIALIZED (SELECT "
        "count(*) FILTER (WHERE y_usable_sites > 0) > 5 OR "
        "(count(*) FILTER (WHERE y_usable_sites > 0))::DOUBLE / count(*) > 0.1 "
        "AS cohort_has_y FROM __dht_ratios"
        "), __dht_called AS NOT MATERIALIZED (SELECT r.*, c.cohort_has_y, "
        "CASE WHEN y_depth_ratio IS NULL OR (CAST(y_gate AS VARCHAR) = 'cohort' "
        "AND NOT c.cohort_has_y) THEN NULL "
        "WHEN y_depth_ratio > CAST(y_signal_min AS DOUBLE) THEN 'present' "
        "ELSE 'absent' END AS y_signal, "
        "CASE WHEN x_usable_sites >= CAST(min_usable_x_sites AS UBIGINT) "
        "AND x_het_hom_alt_ratio < CAST(xy_max_het_ratio AS DOUBLE) THEN 'XY' "
        "WHEN x_usable_sites >= CAST(min_usable_x_sites AS UBIGINT) "
        "AND x_het_hom_alt_ratio > CAST(xx_min_het_ratio AS DOUBLE) THEN 'XX' "
        "ELSE 'ambiguous' END AS x_call "
        "FROM __dht_ratios r CROSS JOIN __dht_cohort c"
        ") SELECT s.sample_id, s.assembly, i.panel_sha256, "
        "i.autosomal_sites, s.autosomal_genotyped_sites, s.autosomal_depth_mean, "
        "i.x_sites, s.x_usable_sites, s.x_depth_ratio, s.x_hom_ref, s.x_het, s.x_hom_alt, "
        "s.x_het_hom_alt_ratio, s.y_sites, s.y_usable_sites, s.y_depth_ratio, "
        "s.cohort_has_y, s.y_signal, "
        "CASE WHEN s.x_call = 'XX' AND s.y_signal = 'present' THEN 'ambiguous' "
        "ELSE s.x_call END AS inferred_sex, "
        "CASE WHEN s.x_usable_sites = 0 THEN 'no_usable_x_sites' "
        "WHEN s.x_usable_sites < CAST(min_usable_x_sites AS UBIGINT) THEN 'insufficient_x_sites' "
        "WHEN s.autosomal_genotyped_sites = 0 THEN 'no_autosomal_depth' "
        "ELSE 'ok' END AS status, "
        "list_filter([CASE WHEN s.x_call = 'XY' AND s.y_signal = 'absent' THEN "
        "'apparent_y_loss' END, CASE WHEN s.x_call = 'XX' AND s.y_signal = 'present' THEN "
        "'apparent_y_with_xx_dosage' END], lambda flag: flag IS NOT NULL) AS review_flags, "
        "'review_only_x_y_dosage_evidence; not a clinical or legal determination of sex'"
        "::VARCHAR AS interpretation, "
        "CAST(min_depth AS UBIGINT) AS applied_min_depth, "
        "CAST(min_sex_site_depth AS UBIGINT) AS applied_min_sex_site_depth, "
        "CAST(min_het_balance AS DOUBLE) AS applied_min_het_balance, "
        "CAST(hom_balance_cutoff AS DOUBLE) AS applied_hom_balance_cutoff, "
        "CAST(min_usable_x_sites AS UBIGINT) AS applied_min_usable_x_sites, "
        "CAST(xy_max_het_ratio AS DOUBLE) AS applied_xy_max_het_ratio, "
        "CAST(xx_min_het_ratio AS DOUBLE) AS applied_xx_min_het_ratio, "
        "CAST(y_signal_min AS DOUBLE) AS applied_y_signal_min, "
        "CAST(y_gate AS VARCHAR) AS applied_y_gate "
        "FROM __dht_called s CROSS JOIN __dht_identity i CROSS JOIN __dht_settings st "
        "WHERE st.valid ORDER BY s.sample_id"
    };

    return duckhts_register_sql_parts(
        registration, sex_sql, sizeof(sex_sql) / sizeof(sex_sql[0]));
}
