#include "duckhts_registration.h"

bool register_duckhts_somalier_vcf_extract_sql(duckhts_registration_t *registration) {
    static const char *const sites_sql[] = {
        "CREATE OR REPLACE MACRO duckhts_somalier_import_sites("
        "path, assembly_name, max_sites := 1000000) AS TABLE "
        "WITH __dht_header AS MATERIALIZED ("
        "SELECT CASE "
        "WHEN count(*) FILTER (WHERE record_type = 'INFO' AND id = 'AF') = 0 THEN "
        "error('duckhts_somalier_import_sites: INFO/AF is not declared in the header') "
        "WHEN count(*) FILTER (WHERE record_type = 'INFO' AND id = 'AF') != 1 THEN "
        "error('duckhts_somalier_import_sites: INFO/AF must have one header declaration') "
        "WHEN count(*) FILTER (WHERE record_type = 'INFO' AND id = 'AF' "
        "AND number = 'A' AND value_type = 'Float') != 1 THEN "
        "error('duckhts_somalier_import_sites: INFO/AF must declare Number=A,Type=Float') "
        "ELSE true END AS valid FROM read_hts_header(path)"
        "), __dht_source AS MATERIALIZED ("
        "SELECT CAST(CHROM AS VARCHAR) AS region, CAST(POS AS UBIGINT) AS position, "
        "CAST(REF AS VARCHAR) AS source_ref, CAST(ALT AS VARCHAR[]) AS source_alt, "
        "CAST(FILTER AS VARCHAR[]) AS source_filter, CAST(INFO_AF AS FLOAT[]) AS source_af "
        "FROM read_bcf(path, samples := '', scan_mode := 'sequential', "
        "decode_error_policy := 'error')"
        "), __dht_autosomal AS MATERIALIZED ("
        "SELECT * FROM __dht_source WHERE region NOT IN "
        "('X', 'chrX', 'NC_000023.10', 'NC_000023.11', "
        "'Y', 'chrY', 'NC_000024.9', 'NC_000024.10')"
        "), __dht_validation AS MATERIALIZED ("
        "SELECT CASE "
        "WHEN assembly_name IS NULL OR CAST(assembly_name AS VARCHAR) = '' "
        "OR octet_length(encode(CAST(assembly_name AS VARCHAR))) > 1024 THEN "
        "error('duckhts_somalier_import_sites: assembly must be a nonempty string of at most 1024 bytes') "
        "WHEN max_sites IS NULL OR TRY_CAST(max_sites AS HUGEINT) IS NULL "
        "OR TRY_CAST(max_sites AS HUGEINT) < 1 "
        "OR TRY_CAST(max_sites AS HUGEINT) > 100000000 "
        "OR TRY_CAST(max_sites AS DOUBLE) != TRY_CAST(max_sites AS HUGEINT) THEN "
        "error('duckhts_somalier_import_sites: max_sites must be an integer in [1, 100000000]') "
        "WHEN (SELECT count(*) FROM __dht_source) > TRY_CAST(max_sites AS HUGEINT) THEN "
        "error('duckhts_somalier_import_sites: sites file exceeds max_sites') "
        "WHEN count(*) = 0 THEN "
        "error('duckhts_somalier_import_sites: sites file has no autosomal records') "
        "WHEN count(*) FILTER (WHERE region IS NULL OR region = '' "
        "OR octet_length(encode(region)) > 1024 OR position IS NULL OR position = 0) != 0 THEN "
        "error('duckhts_somalier_import_sites: region must be 1..1024 bytes and position must be positive') "
        "WHEN count(*) FILTER (WHERE source_ref IS NULL OR len(source_ref) != 1 "
        "OR source_ref NOT IN ('A', 'C', 'G', 'T') OR source_alt IS NULL "
        "OR len(source_alt) != 1 OR source_alt[1] IS NULL OR len(source_alt[1]) != 1 "
        "OR source_alt[1] NOT IN ('A', 'C', 'G', 'T') "
        "OR source_ref = source_alt[1]) != 0 THEN "
        "error('duckhts_somalier_import_sites: records must be distinct uppercase canonical biallelic SNVs') "
        "WHEN count(*) FILTER (WHERE source_af IS NULL OR len(source_af) != 1 "
        "OR source_af[1] IS NULL OR NOT isfinite(source_af[1]) "
        "OR source_af[1] < 0 OR source_af[1] > 1) != 0 THEN "
        "error('duckhts_somalier_import_sites: every record must have one finite INFO/AF value in [0, 1]') "
        "WHEN count(*) != count(DISTINCT struct_pack(region := region, pos1 := position)) THEN "
        "error('duckhts_somalier_import_sites: duplicate physical site') "
        "ELSE true END AS valid FROM __dht_autosomal"
        "), __dht_oriented AS MATERIALIZED ("
        "SELECT CAST(assembly_name AS VARCHAR) AS assembly, region, position, "
        "CASE WHEN source_ref < source_alt[1] THEN source_ref ELSE source_alt[1] END "
        "AS allele_a, "
        "CASE WHEN source_ref < source_alt[1] THEN source_alt[1] ELSE source_ref END "
        "AS allele_b, "
        "CAST(CASE WHEN source_ref < source_alt[1] THEN source_af[1] "
        "ELSE 1.0 - source_af[1] END AS DOUBLE) AS population_b_af, "
        "source_ref, source_alt[1] AS source_alt, CAST(source_af[1] AS DOUBLE) AS source_alt_af, "
        "source_filter FROM __dht_autosomal CROSS JOIN __dht_header h "
        "CROSS JOIN __dht_validation v WHERE h.valid AND v.valid"
        ") SELECT assembly, "
        "CAST(row_number() OVER (ORDER BY region, position) - 1 AS UBIGINT) AS site_index, "
        "region, position, allele_a, allele_b, population_b_af, "
        "CAST(path AS VARCHAR) AS source_path, source_ref, source_alt, source_alt_af, source_filter "
        "FROM __dht_oriented ORDER BY region, position"
    };
    static const char *const counts_sql[] = {
        "CREATE OR REPLACE MACRO duckhts_somalier_vcf_counts("
        "path, panel_table, samples := NULL, filter_policy := 'pass_or_unapplied') AS TABLE "
        "WITH __dht_filter_policy AS MATERIALIZED ("
        "SELECT CASE WHEN filter_policy IS NULL OR CAST(filter_policy AS VARCHAR) "
        "NOT IN ('pass_or_unapplied', 'include_all', 'error') THEN "
        "error('duckhts_somalier_vcf_counts: filter_policy must be pass_or_unapplied, "
        "include_all or error') ELSE CAST(filter_policy AS VARCHAR) END AS filter_policy"
        "), __dht_ad_header AS MATERIALIZED ("
        "SELECT CASE "
        "WHEN count(*) FILTER (WHERE record_type = 'FORMAT' AND id = 'AD') = 0 THEN "
        "error('duckhts_somalier_vcf_counts: FORMAT/AD is not declared in the header') "
        "WHEN count(*) FILTER (WHERE record_type = 'FORMAT' AND id = 'AD') != 1 THEN "
        "error('duckhts_somalier_vcf_counts: FORMAT/AD must have one header declaration') "
        "WHEN count(*) FILTER (WHERE record_type = 'FORMAT' AND id = 'AD' "
        "AND number = 'R' AND value_type = 'Integer') != 1 THEN "
        "error('duckhts_somalier_vcf_counts: FORMAT/AD must declare Number=R,Type=Integer') "
        "ELSE true END AS valid FROM read_hts_header(path)"
        "), __dht_panel_identity AS MATERIALIZED ("
        "SELECT duckhts_somalier_panel_sha256(panel_table) AS panel_sha256"
        "), __dht_panel_raw AS MATERIALIZED ("
        "SELECT CAST(assembly AS VARCHAR) AS assembly, "
        "CAST(site_index AS UBIGINT) AS site_index, CAST(region AS VARCHAR) AS region, "
        "CAST(position AS UBIGINT) AS position, CAST(allele_a AS VARCHAR) AS allele_a, "
        "CAST(allele_b AS VARCHAR) AS allele_b FROM query_table(panel_table)"
        "), __dht_panel AS MATERIALIZED ("
        "SELECT p.* FROM __dht_panel_raw p CROSS JOIN __dht_ad_header h "
        "CROSS JOIN __dht_panel_identity i WHERE h.valid AND i.panel_sha256 IS NOT NULL",
        "), __dht_source_records AS MATERIALIZED ("
        "SELECT record_index, CAST(CHROM AS VARCHAR) AS source_region, "
        "CAST(POS AS UBIGINT) AS source_position, CAST(REF AS VARCHAR) AS source_ref, "
        "CAST(ALT AS VARCHAR[]) AS source_alt, CAST(FILTER AS VARCHAR[]) AS source_filter, "
        "list_concat([CAST(REF AS VARCHAR)], CAST(ALT AS VARCHAR[])) AS source_alleles, "
        "calls FROM read_geno(path, samples := samples, scan_mode := 'sequential', "
        "decode_error_policy := 'error', format_fields := ['AD'], include_filter := true)"
        "), __dht_candidates AS MATERIALIZED ("
        "SELECT p.*, r.record_index AS source_record_index, r.source_ref, r.source_alt, "
        "r.source_filter, "
        "r.source_alleles, r.calls, "
        "list_position(r.source_alleles, p.allele_a) - 1 AS source_allele_a_index, "
        "list_position(r.source_alleles, p.allele_b) - 1 AS source_allele_b_index, "
        "CASE WHEN r.record_index IS NULL THEN false ELSE "
        "len(list_filter(r.source_alleles, a -> a = '*' OR regexp_matches(a, '^<.*>$') "
        "OR strpos(a, '[') > 0 OR strpos(a, ']') > 0)) > 0 END AS symbolic_allele "
        "FROM __dht_panel p LEFT JOIN __dht_source_records r "
        "ON r.source_region = p.region AND r.source_position = p.position"
        "), __dht_candidate_summary AS MATERIALIZED ("
        "SELECT site_index, count(source_record_index) AS source_record_count, "
        "count(*) FILTER (WHERE source_record_index IS NOT NULL "
        "AND len(list_distinct(source_alleles)) != len(source_alleles)) "
        "AS duplicate_allele_records FROM __dht_candidates GROUP BY site_index"
        "), __dht_record_validation AS MATERIALIZED ("
        "SELECT CASE "
        "WHEN count(*) FILTER (WHERE source_record_count > 1) != 0 THEN "
        "error('duckhts_somalier_vcf_counts: multiple source records occur at a panel site') "
        "WHEN count(*) FILTER (WHERE duplicate_allele_records != 0) != 0 THEN "
        "error('duckhts_somalier_vcf_counts: a source record has duplicate REF/ALT alleles') "
        "ELSE true END AS valid FROM __dht_candidate_summary",
        "), __dht_candidate_calls AS MATERIALIZED ("
        "SELECT c.site_index, c.source_record_index, call.sample_index, "
        "CASE WHEN typeof(call.format.AD) = 'INTEGER[]' "
        "THEN CAST(call.format.AD AS INTEGER[]) ELSE NULL::INTEGER[] END AS ad, "
        "c.source_alleles, c.source_allele_a_index, c.source_allele_b_index, "
        "c.symbolic_allele FROM __dht_candidates c, unnest(c.calls) AS u(call) "
        "WHERE c.source_record_index IS NOT NULL"
        "), __dht_ad_validation AS MATERIALIZED ("
        "SELECT CASE "
        "WHEN count(*) FILTER (WHERE ad IS NOT NULL "
        "AND NOT (len(ad) = 1 AND ad[1] IS NULL) "
        "AND len(ad) != len(source_alleles)) != 0 THEN "
        "error('duckhts_somalier_vcf_counts: FORMAT/AD cardinality does not match REF plus ALT') "
        "WHEN count(*) FILTER (WHERE ad IS NOT NULL "
        "AND len(list_filter(ad, value -> value < 0)) != 0) != 0 THEN "
        "error('duckhts_somalier_vcf_counts: FORMAT/AD counts must be non-negative') "
        "ELSE true END AS valid FROM __dht_candidate_calls"
        "), __dht_filter_validation AS MATERIALIZED ("
        "SELECT CASE WHEN fp.filter_policy = 'error' AND count(*) FILTER ("
        "WHERE c.source_record_index IS NOT NULL AND c.source_filter IS NOT NULL "
        "AND c.source_filter != ['PASS']) != 0 THEN "
        "error('duckhts_somalier_vcf_counts: a panel record has a failing FILTER') "
        "ELSE true END AS valid FROM __dht_candidates c CROSS JOIN __dht_filter_policy fp "
        "GROUP BY fp.filter_policy"
        "), __dht_samples AS MATERIALIZED ("
        "SELECT CAST(sample_index AS UINTEGER) AS sample_index, "
        "CAST(sample_name AS VARCHAR) AS sample_id "
        "FROM read_bcf_samples(path, samples := samples)"
        "), __dht_grid AS MATERIALIZED ("
        "SELECT s.sample_index, s.sample_id, p.* FROM __dht_samples s CROSS JOIN __dht_panel p"
        "), __dht_evidence AS NOT MATERIALIZED ("
        "SELECT g.*, c.source_record_index, c.source_ref, c.source_alt, c.source_filter, "
        "c.source_alleles, c.source_allele_a_index, c.source_allele_b_index, "
        "c.symbolic_allele, cc.ad, fp.filter_policy FROM __dht_grid g "
        "LEFT JOIN __dht_candidates c USING (site_index) "
        "LEFT JOIN __dht_candidate_calls cc "
        "ON cc.site_index = g.site_index AND cc.sample_index = g.sample_index "
        "CROSS JOIN __dht_filter_policy fp",
        ") SELECT sample_id, CAST(path AS VARCHAR) AS source_path, assembly, site_index, "
        "region, position, allele_a, allele_b, "
        "CASE WHEN source_record_index IS NULL OR symbolic_allele "
        "OR source_allele_a_index IS NULL OR source_allele_b_index IS NULL "
        "OR (filter_policy = 'pass_or_unapplied' AND source_filter IS NOT NULL "
        "AND source_filter != ['PASS']) "
        "OR ad IS NULL OR (len(ad) = 1 AND ad[1] IS NULL) "
        "OR len(list_filter(ad, value -> value IS NULL)) != 0 THEN NULL::UBIGINT "
        "ELSE CAST(ad[source_allele_a_index + 1] AS UBIGINT) END AS a, "
        "CASE WHEN source_record_index IS NULL OR symbolic_allele "
        "OR source_allele_a_index IS NULL OR source_allele_b_index IS NULL "
        "OR (filter_policy = 'pass_or_unapplied' AND source_filter IS NOT NULL "
        "AND source_filter != ['PASS']) "
        "OR ad IS NULL OR (len(ad) = 1 AND ad[1] IS NULL) "
        "OR len(list_filter(ad, value -> value IS NULL)) != 0 THEN NULL::UBIGINT "
        "ELSE CAST(ad[source_allele_b_index + 1] AS UBIGINT) END AS b, "
        "CASE WHEN source_record_index IS NULL OR symbolic_allele "
        "OR source_allele_a_index IS NULL OR source_allele_b_index IS NULL "
        "OR (filter_policy = 'pass_or_unapplied' AND source_filter IS NOT NULL "
        "AND source_filter != ['PASS']) "
        "OR ad IS NULL OR (len(ad) = 1 AND ad[1] IS NULL) "
        "OR len(list_filter(ad, value -> value IS NULL)) != 0 THEN NULL::UBIGINT "
        "ELSE CAST(list_sum(ad) - ad[source_allele_a_index + 1] "
        "- ad[source_allele_b_index + 1] AS UBIGINT) END AS other, "
        "'vcf_bcf_format_ad'::VARCHAR AS source_method, "
        "'declared_alleles_only'::VARCHAR AS count_scope, "
        "filter_policy AS \"filter_policy\", "
        "CASE WHEN source_record_index IS NULL THEN 'unavailable_no_record' "
        "WHEN filter_policy = 'pass_or_unapplied' AND source_filter IS NOT NULL "
        "AND source_filter != ['PASS'] THEN 'unavailable_filtered' "
        "WHEN symbolic_allele THEN 'unavailable_symbolic_allele' "
        "WHEN source_allele_a_index IS NULL OR source_allele_b_index IS NULL "
        "THEN 'unavailable_allele_mismatch' "
        "WHEN ad IS NULL THEN 'unavailable_ad_absent' "
        "WHEN (len(ad) = 1 AND ad[1] IS NULL) "
        "OR len(list_filter(ad, value -> value IS NULL)) != 0 "
        "THEN 'unavailable_ad_missing' ELSE 'measured' END::VARCHAR AS status, "
        "source_record_index, sample_index AS source_sample_index, source_ref, source_alt, "
        "source_filter, "
        "CAST(source_allele_a_index AS UINTEGER) AS source_allele_a_index, "
        "CAST(source_allele_b_index AS UINTEGER) AS source_allele_b_index "
        "FROM __dht_evidence CROSS JOIN __dht_record_validation rv "
        "CROSS JOIN __dht_ad_validation av CROSS JOIN __dht_filter_validation fv "
        "WHERE rv.valid AND av.valid AND fv.valid"
    };

    return duckhts_register_sql_parts(
               registration, sites_sql, sizeof(sites_sql) / sizeof(sites_sql[0])) &&
           duckhts_register_sql_parts(
               registration, counts_sql, sizeof(counts_sql) / sizeof(counts_sql[0]));
}
